/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package IGU;

import java.awt.Color;
import javax.swing.Icon;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import logica.Cliente;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Juan Romero
 */
public class Inicio_de_sesion extends javax.swing.JFrame {
    
    /**
     * Creates new form Inicio_de_sesion
     */
    public Inicio_de_sesion() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/favicon/Nuevo_logo_de_Luminous_Horizons.png")).getImage());
        this.setResizable(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LuminousHorizons = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        labelPassword = new javax.swing.JLabel();
        inputUsuario = new javax.swing.JTextField();
        inputPassword = new javax.swing.JPasswordField();
        btn_inicio_de_sesion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        LabelDerechosDeAutor = new javax.swing.JLabel();
        btn_recuperarContrasena = new javax.swing.JButton();
        btn_ingresar_como_invitado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INICIO DE SESIÓN | Luminous Horizons");

        jPanel1.setBackground(new java.awt.Color(24, 7, 43));
        jPanel1.setMinimumSize(new java.awt.Dimension(670, 687));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LuminousHorizons.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/Nuevo logo de Luminous Horizons.png"))); // NOI18N
        jPanel1.add(LuminousHorizons, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        labelUsuario.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        labelUsuario.setForeground(new java.awt.Color(226, 203, 253));
        labelUsuario.setText("Usuario:");
        jPanel1.add(labelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, -1, -1));

        labelPassword.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        labelPassword.setForeground(new java.awt.Color(226, 203, 253));
        labelPassword.setText("Contraseña:");
        jPanel1.add(labelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, -1, -1));

        inputUsuario.setBackground(new java.awt.Color(24, 7, 43));
        inputUsuario.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        inputUsuario.setForeground(new java.awt.Color(102, 102, 102));
        inputUsuario.setText("Ingresa tu usuario");
        inputUsuario.setToolTipText("Usuario");
        inputUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(226, 203, 253), 3, true), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        inputUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputUsuarioMouseClicked(evt);
            }
        });
        inputUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(inputUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 520, 40));

        inputPassword.setBackground(new java.awt.Color(24, 7, 43));
        inputPassword.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        inputPassword.setForeground(new java.awt.Color(102, 102, 102));
        inputPassword.setText("••••••••••");
        inputPassword.setToolTipText("Contraseña");
        inputPassword.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(226, 203, 253), 3, true)));
        inputPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputPasswordMouseClicked(evt);
            }
        });
        inputPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(inputPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 500, 520, 40));

        btn_inicio_de_sesion.setBackground(new java.awt.Color(226, 203, 253));
        btn_inicio_de_sesion.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btn_inicio_de_sesion.setForeground(new java.awt.Color(24, 7, 43));
        btn_inicio_de_sesion.setText("Iniciar sesión");
        btn_inicio_de_sesion.setBorderPainted(false);
        btn_inicio_de_sesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_inicio_de_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inicio_de_sesionActionPerformed(evt);
            }
        });
        jPanel1.add(btn_inicio_de_sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 600, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/wave-lavanda.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 140));

        LabelDerechosDeAutor.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        LabelDerechosDeAutor.setForeground(new java.awt.Color(153, 153, 153));
        LabelDerechosDeAutor.setText("©CopyRigth 2023 Luminous Horizons");
        jPanel1.add(LabelDerechosDeAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 660, -1, -1));

        btn_recuperarContrasena.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_recuperarContrasena.setForeground(new java.awt.Color(255, 255, 255));
        btn_recuperarContrasena.setText("Recuperar contraseña");
        btn_recuperarContrasena.setBorder(null);
        btn_recuperarContrasena.setContentAreaFilled(false);
        btn_recuperarContrasena.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_recuperarContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_recuperarContrasenaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_recuperarContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 550, -1, -1));

        btn_ingresar_como_invitado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_ingresar_como_invitado.setForeground(new java.awt.Color(255, 255, 255));
        btn_ingresar_como_invitado.setText("Ingresar como invitado");
        btn_ingresar_como_invitado.setBorder(null);
        btn_ingresar_como_invitado.setContentAreaFilled(false);
        btn_ingresar_como_invitado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ingresar_como_invitado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresar_como_invitadoActionPerformed(evt);
            }
        });
        jPanel1.add(btn_ingresar_como_invitado, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 550, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_inicio_de_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inicio_de_sesionActionPerformed
        try {                                                     
            Cliente cliente = new Cliente(inputUsuario.getText(), String.valueOf(inputPassword.getPassword()));
            String rpta = null;
            rpta = cliente.Autenticar();
            String nombre = cliente.obtenerNombreClientePorUsuario(inputUsuario.getText());
            String genero = cliente.obtenerGeneroClientePorUsuario(inputUsuario.getText());
            if(rpta.equals("")) {
                Icon icono = new ImageIcon(getClass().getResource("/icon/verificacion.png"));
                String saludo = null;
                if (genero.equals("hombre")) {
                    saludo = "Bienvenido";
                }else if (genero.equals("mujer")) {
                    saludo = "Bienvenida";
                }
                JOptionPane.showMessageDialog(null, "Se incio sesión de manera exitosa, " + nombre + " ¡"+ saludo +"!", "VALIDACIÓN DE CREDENCIALES",JOptionPane.INFORMATION_MESSAGE, icono);
                /**
                * Este procedimiento permite mostrar la ventana siguiente
                */
                Panel_de_control panel_de_control = new Panel_de_control();
                panel_de_control.setVisible(true);
                panel_de_control.setLocationRelativeTo(null);
                panel_de_control.ColocarNombre(nombre);
                panel_de_control.colorcarAvatar(genero);
                dispose();
            }else {
                Icon icono = new ImageIcon(getClass().getResource("/icon/error.png"));
                JOptionPane.showMessageDialog(null, "Usuario o clave incorrecta", "VALIDACIÓN DE CREDENCIALES",JOptionPane.ERROR_MESSAGE, icono);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Inicio_de_sesion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Inicio_de_sesion.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btn_inicio_de_sesionActionPerformed

    private void inputUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputUsuarioActionPerformed

    private void inputUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputUsuarioMouseClicked
        if (inputUsuario.getText().equals("Ingresa tu usuario")){
            inputUsuario.setText("");
            inputUsuario.setForeground(Color.WHITE);
        }
        if(String.valueOf(inputPassword.getPassword()).isEmpty()){
            inputPassword.setText("••••••••••");
            inputPassword.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_inputUsuarioMouseClicked

    private void inputPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPasswordActionPerformed

    private void inputPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputPasswordMouseClicked
        if (String.valueOf(inputPassword.getPassword()).equals("••••••••••")) {
            inputPassword.setText("");
            inputPassword.setForeground(Color.WHITE);
        }
        if (inputUsuario.getText().isEmpty()) {
            inputUsuario.setText("Ingresa tu usuario");
            inputUsuario.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_inputPasswordMouseClicked

    private void btn_recuperarContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_recuperarContrasenaActionPerformed
        RecuperarContrasena recuperarContrasena = new RecuperarContrasena();
        recuperarContrasena.setVisible(true);
        recuperarContrasena.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_recuperarContrasenaActionPerformed

    private void btn_ingresar_como_invitadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresar_como_invitadoActionPerformed
        Panel_de_invitado panel_de_invitado = null;
        try {
            panel_de_invitado = new Panel_de_invitado();
        } catch (SQLException ex) {
            Logger.getLogger(Inicio_de_sesion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Inicio_de_sesion.class.getName()).log(Level.SEVERE, null, ex);
        }
        panel_de_invitado.setVisible(true);
        panel_de_invitado.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_btn_ingresar_como_invitadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio_de_sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio_de_sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio_de_sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio_de_sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio_de_sesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelDerechosDeAutor;
    private javax.swing.JLabel LuminousHorizons;
    private javax.swing.JButton btn_ingresar_como_invitado;
    private javax.swing.JButton btn_inicio_de_sesion;
    private javax.swing.JButton btn_recuperarContrasena;
    private javax.swing.JPasswordField inputPassword;
    private javax.swing.JTextField inputUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelUsuario;
    // End of variables declaration//GEN-END:variables
}
