/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package IGU;

import java.sql.SQLException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import logica.Configuraciones;

/**
 *
 * @author Juan Romero
 */
public class NuevaContrasena extends javax.swing.JFrame {
    Configuraciones configuraciones;
    protected static String miEmail;
    
    /**
     * Creates new form NuevasContrasenas
     */
    public NuevaContrasena() {
        initComponents();
        configuraciones = new Configuraciones();
        setIconImage(new ImageIcon(getClass().getResource("/favicon/Nuevo_logo_de_Luminous_Horizons.png")).getImage());
        this.setResizable(false);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        input_contrasena = new javax.swing.JPasswordField();
        input_repetir_contrasena = new javax.swing.JPasswordField();
        btn_guardar = new IGU.util.ButtonGradient();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NUEVA CONTRASEÑA | Luminous Horizons");

        jPanel1.setBackground(new java.awt.Color(24, 7, 43));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/Nuevo logo de Luminous Horizons.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(226, 203, 253));
        jLabel2.setText("Contraseña");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(226, 203, 253));
        jLabel3.setText("Repetir contraseña");

        input_contrasena.setBackground(new java.awt.Color(24, 7, 43));
        input_contrasena.setForeground(new java.awt.Color(255, 255, 255));
        input_contrasena.setToolTipText("Al menos la contraseña debe de tener una longitud de 8 digitos y debe de tener al menos una mayúscula y un caracter especial.");
        input_contrasena.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(226, 203, 253), 3, true));
        input_contrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_contrasenaActionPerformed(evt);
            }
        });

        input_repetir_contrasena.setBackground(new java.awt.Color(24, 7, 43));
        input_repetir_contrasena.setForeground(new java.awt.Color(255, 255, 255));
        input_repetir_contrasena.setToolTipText("Al menos la contraseña debe de tener una longitud de 8 digitos y debe de tener al menos una mayúscula y un caracter especial.");
        input_repetir_contrasena.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(226, 203, 253), 3, true));

        btn_guardar.setText("Guardar");
        btn_guardar.setColor1(new java.awt.Color(153, 0, 204));
        btn_guardar.setColor2(new java.awt.Color(0, 0, 0));
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(input_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(input_repetir_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(input_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(input_repetir_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        if (configuraciones.isStrongPassword(input_contrasena.getPassword())) {
            if (Arrays.equals(input_contrasena.getPassword(), input_repetir_contrasena.getPassword())) {
                try {
                    configuraciones.actualizarContrasena(miEmail, input_contrasena.getPassword());
                    configuraciones.standarCodigoVerificacion(miEmail);
                } catch (SQLException ex) {
                    Logger.getLogger(NuevaContrasena.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(NuevaContrasena.class.getName()).log(Level.SEVERE, null, ex);
                }
                Icon icono = new ImageIcon(getClass().getResource("/icon/verificacion.png"));
                JOptionPane.showMessageDialog(null, "Se restablecio la contraseña de manera correcta",
                        "MENSAJE DE RECUPERACIÓN", JOptionPane.WARNING_MESSAGE, icono);
                dispose();
            }else {
                Icon icono = new ImageIcon(getClass().getResource("/icon/error.png"));
                JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden",
                        "ADVERTENCIA", JOptionPane.ERROR_MESSAGE, icono);
            }
        }else {
            Icon icono = new ImageIcon(getClass().getResource("/icon/error.png"));
            JOptionPane.showMessageDialog(null, "Las contraseñas no es segura",
                        "ADVERTENCIA", JOptionPane.ERROR_MESSAGE, icono);
        }
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void input_contrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_contrasenaActionPerformed
        
    }//GEN-LAST:event_input_contrasenaActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private IGU.util.ButtonGradient btn_guardar;
    private javax.swing.JPasswordField input_contrasena;
    private javax.swing.JPasswordField input_repetir_contrasena;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
