package IGU;

import javax.swing.ImageIcon;

/**
 *
 * @author Juan Romero
 */
public class Panel_de_control extends javax.swing.JFrame {

    public void ColocarNombre(String Mensaje)
    {
        label_nombreUsuario.setText(Mensaje);
    }
    /**
     * Creates new form Panel_de_control
     */
    public Panel_de_control() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/favicon/luminous_horizons.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnEmpleados = new javax.swing.JButton();
        btnEmpleados1 = new javax.swing.JButton();
        btnEmpleados2 = new javax.swing.JButton();
        btnEmpleados3 = new javax.swing.JButton();
        btnEmpleados4 = new javax.swing.JButton();
        LabelDerechosDeAutor = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        avatarUser1 = new logica.util.AvatarUser();
        label_nombreUsuario = new javax.swing.JLabel();
        btn_panel_control = new swing.ButtonGradient();
        btn_salir1 = new swing.ButtonGradient();
        btn_configuraciones = new swing.ButtonGradient();
        btn_analisis = new swing.ButtonGradient();
        btn_informes = new swing.ButtonGradient();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Panel de control");
        setMinimumSize(new java.awt.Dimension(670, 687));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEmpleados.setBackground(new java.awt.Color(51, 51, 51));
        btnEmpleados.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEmpleados.setForeground(new java.awt.Color(255, 255, 255));
        btnEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/clientes.png"))); // NOI18N
        btnEmpleados.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(192, 130, 97), 3, true), "Clientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        btnEmpleados.setContentAreaFilled(false);
        btnEmpleados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 180, 170));

        btnEmpleados1.setBackground(new java.awt.Color(51, 51, 51));
        btnEmpleados1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEmpleados1.setForeground(new java.awt.Color(255, 255, 255));
        btnEmpleados1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/empleados.png"))); // NOI18N
        btnEmpleados1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(192, 130, 97), 3, true), "Empleados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        btnEmpleados1.setContentAreaFilled(false);
        btnEmpleados1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnEmpleados1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 180, 170));

        btnEmpleados2.setBackground(new java.awt.Color(51, 51, 51));
        btnEmpleados2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEmpleados2.setForeground(new java.awt.Color(255, 255, 255));
        btnEmpleados2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/reserva.png"))); // NOI18N
        btnEmpleados2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(192, 130, 97), 3, true), "Reservas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        btnEmpleados2.setContentAreaFilled(false);
        btnEmpleados2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnEmpleados2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 180, 170));

        btnEmpleados3.setBackground(new java.awt.Color(51, 51, 51));
        btnEmpleados3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEmpleados3.setForeground(new java.awt.Color(255, 255, 255));
        btnEmpleados3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/usuario.png"))); // NOI18N
        btnEmpleados3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(192, 130, 97), 3, true), "Usuarios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        btnEmpleados3.setContentAreaFilled(false);
        btnEmpleados3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnEmpleados3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 180, 170));

        btnEmpleados4.setBackground(new java.awt.Color(51, 51, 51));
        btnEmpleados4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEmpleados4.setForeground(new java.awt.Color(255, 255, 255));
        btnEmpleados4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/viajes.png"))); // NOI18N
        btnEmpleados4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(192, 130, 97), 3, true), "Viajes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        btnEmpleados4.setContentAreaFilled(false);
        btnEmpleados4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnEmpleados4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 180, 170));

        LabelDerechosDeAutor.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        LabelDerechosDeAutor.setForeground(new java.awt.Color(153, 153, 153));
        LabelDerechosDeAutor.setText("©CopyRigth 2023 Luminous Horizons");
        jPanel1.add(LabelDerechosDeAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 630, -1, -1));

        Menu.setBackground(new java.awt.Color(192, 130, 97));
        Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        avatarUser1.setBackground(new java.awt.Color(255, 255, 255));
        avatarUser1.setBorderSize(3);
        avatarUser1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/user_hombre.png"))); // NOI18N
        Menu.add(avatarUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 156, 158));

        label_nombreUsuario.setBackground(new java.awt.Color(0, 0, 0));
        label_nombreUsuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_nombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        label_nombreUsuario.setText("Nombre");
        Menu.add(label_nombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        btn_panel_control.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/panel-de-control.png"))); // NOI18N
        btn_panel_control.setText("            Panel de control");
        btn_panel_control.setColor1(new java.awt.Color(154, 59, 59));
        btn_panel_control.setColor2(new java.awt.Color(102, 102, 102));
        btn_panel_control.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_panel_control.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_panel_controlActionPerformed(evt);
            }
        });
        Menu.add(btn_panel_control, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 200, 30));

        btn_salir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cerrar-sesion.png"))); // NOI18N
        btn_salir1.setText("           Cerrar sesión");
        btn_salir1.setColor1(new java.awt.Color(154, 59, 59));
        btn_salir1.setColor2(new java.awt.Color(102, 102, 102));
        btn_salir1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_salir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salir1ActionPerformed(evt);
            }
        });
        Menu.add(btn_salir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 600, 200, 30));

        btn_configuraciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/configuracion.png"))); // NOI18N
        btn_configuraciones.setText("         Configuraciones");
        btn_configuraciones.setColor1(new java.awt.Color(154, 59, 59));
        btn_configuraciones.setColor2(new java.awt.Color(102, 102, 102));
        btn_configuraciones.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_configuraciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_configuracionesActionPerformed(evt);
            }
        });
        Menu.add(btn_configuraciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 200, 30));

        btn_analisis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/analisis-de-mercado.png"))); // NOI18N
        btn_analisis.setText("                        Análisis");
        btn_analisis.setColor1(new java.awt.Color(154, 59, 59));
        btn_analisis.setColor2(new java.awt.Color(102, 102, 102));
        btn_analisis.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_analisis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_analisisActionPerformed(evt);
            }
        });
        Menu.add(btn_analisis, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 200, 30));

        btn_informes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/informe-seo.png"))); // NOI18N
        btn_informes.setText("                       Informes");
        btn_informes.setColor1(new java.awt.Color(154, 59, 59));
        btn_informes.setColor2(new java.awt.Color(102, 102, 102));
        btn_informes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_informes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_informesActionPerformed(evt);
            }
        });
        Menu.add(btn_informes, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 200, 30));

        jPanel1.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(759, 0, 289, 670));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/avion.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 540, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_panel_controlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_panel_controlActionPerformed
        
    }//GEN-LAST:event_btn_panel_controlActionPerformed

    private void btn_salir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salir1ActionPerformed
        Inicio_de_sesion inicio_de_sesion = new Inicio_de_sesion();
        inicio_de_sesion.setVisible(true);
        inicio_de_sesion.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_btn_salir1ActionPerformed

    private void btn_configuracionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_configuracionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_configuracionesActionPerformed

    private void btn_analisisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_analisisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_analisisActionPerformed

    private void btn_informesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_informesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_informesActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelDerechosDeAutor;
    private javax.swing.JPanel Menu;
    private logica.util.AvatarUser avatarUser1;
    private javax.swing.JButton btnEmpleados;
    private javax.swing.JButton btnEmpleados1;
    private javax.swing.JButton btnEmpleados2;
    private javax.swing.JButton btnEmpleados3;
    private javax.swing.JButton btnEmpleados4;
    private swing.ButtonGradient btn_analisis;
    private swing.ButtonGradient btn_configuraciones;
    private swing.ButtonGradient btn_informes;
    private swing.ButtonGradient btn_panel_control;
    private swing.ButtonGradient btn_salir1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_nombreUsuario;
    // End of variables declaration//GEN-END:variables
}
