/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package IGU;

import java.util.Arrays;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.Icon;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan Romero
 */
public class Registro_de_usuarios extends javax.swing.JFrame {
    
    // Función para validar email
    
    public boolean isValidEmail(String email) {
        // Patrón de expresión regular para verificar direcciones de correo electrónico
        String regex = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$";

        // Compila la expresión regular en un patrón
        Pattern pattern = Pattern.compile(regex);

        // Crea un objeto Matcher para la dirección de correo electrónico proporcionada
        Matcher matcher = pattern.matcher(email);

        // Comprueba si la dirección de correo electrónico coincide con el patrón
        return matcher.matches();
    }

    // Función para validar contraseñas fuertes
    
    public boolean isStrongPassword(char[] password) {
        String passwordStr = new String(password);

        // Verifica si la contraseña tiene al menos 8 caracteres
        if (passwordStr.length() < 8) {
            return false;
        }

        // Verifica si la contraseña contiene al menos una letra mayúscula
        if (!passwordStr.matches(".*[A-Z].*")) {
            return false;
        }

        // Verifica si la contraseña contiene al menos un carácter especial
        if (!passwordStr.matches(".*[!@#$%^&*()].*")) {
            return false;
        }

        // Si pasa todas las verificaciones, la contraseña se considera fuerte
        return true;
    }

    
    /**
     * Creates new form Registro_de_usuarios
     */
    public Registro_de_usuarios() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/favicon/Nuevo_logo_de_Luminous_Horizons.png")).getImage());
        cb_genero.setSelectedIndex(-1);
        this.setResizable(false);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label_titulo = new javax.swing.JLabel();
        label_genero = new javax.swing.JLabel();
        label_nombres = new javax.swing.JLabel();
        label_apellidos = new javax.swing.JLabel();
        label_email = new javax.swing.JLabel();
        label_nombre_usuario = new javax.swing.JLabel();
        label_contrasena = new javax.swing.JLabel();
        label_repetir_contrasena = new javax.swing.JLabel();
        input_nombre_usuario = new javax.swing.JTextField();
        input_nombres = new javax.swing.JTextField();
        input_apellido = new javax.swing.JTextField();
        input_email = new javax.swing.JTextField();
        input_repetir_contrasena = new javax.swing.JPasswordField();
        input_contrasena = new javax.swing.JPasswordField();
        cb_genero = new javax.swing.JComboBox<>();
        btn_registrar = new IGU.util.ButtonGradient();
        btn_limpiar = new IGU.util.ButtonGradient();
        logo = new javax.swing.JLabel();
        checkB_tratamiento = new javax.swing.JCheckBox();
        checkB_terminos = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        popup_terminos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REGISTRO | Luminous Horizons");

        jPanel1.setBackground(new java.awt.Color(24, 7, 43));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_titulo.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        label_titulo.setForeground(new java.awt.Color(226, 203, 253));
        label_titulo.setText("Formulario de registro");
        jPanel1.add(label_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        label_genero.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        label_genero.setForeground(new java.awt.Color(226, 203, 253));
        label_genero.setText("Genero");
        jPanel1.add(label_genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        label_nombres.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        label_nombres.setForeground(new java.awt.Color(226, 203, 253));
        label_nombres.setText("Nombres");
        jPanel1.add(label_nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        label_apellidos.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        label_apellidos.setForeground(new java.awt.Color(226, 203, 253));
        label_apellidos.setText("Apellidos");
        jPanel1.add(label_apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, -1, -1));

        label_email.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        label_email.setForeground(new java.awt.Color(226, 203, 253));
        label_email.setText("Email");
        jPanel1.add(label_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        label_nombre_usuario.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        label_nombre_usuario.setForeground(new java.awt.Color(226, 203, 253));
        label_nombre_usuario.setText("Nombre de usuario");
        jPanel1.add(label_nombre_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, -1, -1));

        label_contrasena.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        label_contrasena.setForeground(new java.awt.Color(226, 203, 253));
        label_contrasena.setText("Contraseña");
        jPanel1.add(label_contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        label_repetir_contrasena.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        label_repetir_contrasena.setForeground(new java.awt.Color(226, 203, 253));
        label_repetir_contrasena.setText("Repetir la contraseña");
        jPanel1.add(label_repetir_contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, -1, -1));

        input_nombre_usuario.setBackground(new java.awt.Color(24, 7, 43));
        input_nombre_usuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        input_nombre_usuario.setForeground(new java.awt.Color(255, 255, 255));
        input_nombre_usuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(226, 203, 253), 3, true));
        jPanel1.add(input_nombre_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 270, 40));

        input_nombres.setBackground(new java.awt.Color(24, 7, 43));
        input_nombres.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        input_nombres.setForeground(new java.awt.Color(255, 255, 255));
        input_nombres.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(226, 203, 253), 3, true));
        jPanel1.add(input_nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 270, 40));

        input_apellido.setBackground(new java.awt.Color(24, 7, 43));
        input_apellido.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        input_apellido.setForeground(new java.awt.Color(255, 255, 255));
        input_apellido.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(226, 203, 253), 3, true));
        jPanel1.add(input_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 270, 40));

        input_email.setBackground(new java.awt.Color(24, 7, 43));
        input_email.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        input_email.setForeground(new java.awt.Color(255, 255, 255));
        input_email.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(226, 203, 253), 3, true));
        jPanel1.add(input_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 270, 40));

        input_repetir_contrasena.setBackground(new java.awt.Color(24, 7, 43));
        input_repetir_contrasena.setForeground(new java.awt.Color(255, 255, 255));
        input_repetir_contrasena.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(226, 203, 253), 3, true));
        jPanel1.add(input_repetir_contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 270, 40));

        input_contrasena.setBackground(new java.awt.Color(24, 7, 43));
        input_contrasena.setForeground(new java.awt.Color(255, 255, 255));
        input_contrasena.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(226, 203, 253), 3, true));
        jPanel1.add(input_contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 270, 40));

        cb_genero.setBackground(new java.awt.Color(24, 7, 43));
        cb_genero.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cb_genero.setForeground(new java.awt.Color(255, 255, 255));
        cb_genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "hombre", "mujer" }));
        cb_genero.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(226, 203, 253), 3, true));
        jPanel1.add(cb_genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 270, 40));

        btn_registrar.setText("Registrar");
        btn_registrar.setColor1(new java.awt.Color(153, 0, 204));
        btn_registrar.setColor2(new java.awt.Color(0, 0, 0));
        btn_registrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 560, -1, -1));

        btn_limpiar.setText("Limpiar");
        btn_limpiar.setColor1(new java.awt.Color(153, 0, 204));
        btn_limpiar.setColor2(new java.awt.Color(0, 0, 0));
        btn_limpiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 560, -1, -1));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/Nuevo logo de Luminous Horizons small.png"))); // NOI18N
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        checkB_tratamiento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        checkB_tratamiento.setForeground(new java.awt.Color(255, 255, 255));
        checkB_tratamiento.setText("Acepto que mis datos sean tratados de acuerdo a la política de privacidad");
        checkB_tratamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkB_tratamientoActionPerformed(evt);
            }
        });
        jPanel1.add(checkB_tratamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, -1, -1));

        checkB_terminos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        checkB_terminos.setForeground(new java.awt.Color(255, 255, 255));
        checkB_terminos.setText("Acepto los terminos y condiciones del programa de Luminous Horizons");
        checkB_terminos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkB_terminosActionPerformed(evt);
            }
        });
        jPanel1.add(checkB_terminos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(226, 203, 253));
        jLabel1.setText("  *");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 500, 30, -1));

        popup_terminos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        popup_terminos.setForeground(new java.awt.Color(226, 203, 253));
        popup_terminos.setText(" *");
        popup_terminos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        popup_terminos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                popup_terminosMouseClicked(evt);
            }
        });
        jPanel1.add(popup_terminos, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 460, 20, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkB_tratamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkB_tratamientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkB_tratamientoActionPerformed

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        // Limpia todos los campos
        input_nombres.setText("");
        input_apellido.setText("");
        input_email.setText("");
        input_nombre_usuario.setText("");
        input_contrasena.setText("");
        input_repetir_contrasena.setText("");
        cb_genero.setSelectedIndex(-1);
        checkB_terminos.setSelected(false);
        checkB_tratamiento.setSelected(false);
        // Regresa al campo principal
        input_nombres.requestFocus();
    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarActionPerformed
        // Validar el email
        boolean emailValido = isValidEmail(input_email.getText());
        System.out.println(emailValido);

        // Validar la contraseña
        boolean contrasenaFuerte = isStrongPassword(input_contrasena.getPassword());

        // Comparar contraseñas
        boolean contrasenasCoinciden = Arrays.equals(input_contrasena.getPassword(), input_repetir_contrasena.getPassword());
        
        boolean verificarCampos = input_nombres.getText().isEmpty() || input_apellido.getText().isEmpty() ||
                input_email.getText().isEmpty() || input_nombre_usuario.getText().isEmpty() ||
                new String(input_contrasena.getPassword()).equals("") || new String(input_repetir_contrasena.getPassword()).equals("") ||
                cb_genero.getSelectedItem().equals("") || checkB_terminos.isSelected() == false ||
                checkB_tratamiento.isSelected() == false;


        // Mensaje de respuesta
        if (emailValido && contrasenaFuerte && contrasenasCoinciden) {
            Icon icono = new ImageIcon(getClass().getResource("/icon/verificacion.png"));
            JOptionPane.showMessageDialog(null, "Se registró con éxito.", "VALIDACIÓN", JOptionPane.WARNING_MESSAGE, icono);
        } else {
            StringBuilder mensaje = new StringBuilder();
            
            if (!emailValido) {
                mensaje.append("El email ").append(input_email.getText()).append(" no es válido.");
            }

            if (!contrasenaFuerte) {
                mensaje.append("\nLa contraseña proporcionada no cumple con las condiciones necesarias para su seguridad.");
            }

            if (!contrasenasCoinciden) {
                mensaje.append("\nLas contraseñas no coinciden.");
            }
            
            if (verificarCampos) {
                mensaje.append("\nCompleta todos los campos de los formularios");
            }
            Icon icono = new ImageIcon(getClass().getResource("/icon/informacion.png"));
            JOptionPane.showMessageDialog(null, mensaje.toString(), "INFORMACIÓN", JOptionPane.WARNING_MESSAGE, icono);
        }
    }//GEN-LAST:event_btn_registrarActionPerformed

    private void checkB_terminosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkB_terminosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkB_terminosActionPerformed

    private void popup_terminosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_popup_terminosMouseClicked
        Terminos_y_condiciones terminos_y_condiciones = new Terminos_y_condiciones();
        terminos_y_condiciones.setVisible(true);
        terminos_y_condiciones.setLocationRelativeTo(null);
    }//GEN-LAST:event_popup_terminosMouseClicked

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private IGU.util.ButtonGradient btn_limpiar;
    private IGU.util.ButtonGradient btn_registrar;
    private javax.swing.JComboBox<String> cb_genero;
    private javax.swing.JCheckBox checkB_terminos;
    private javax.swing.JCheckBox checkB_tratamiento;
    private javax.swing.JTextField input_apellido;
    private javax.swing.JPasswordField input_contrasena;
    private javax.swing.JTextField input_email;
    private javax.swing.JTextField input_nombre_usuario;
    private javax.swing.JTextField input_nombres;
    private javax.swing.JPasswordField input_repetir_contrasena;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_apellidos;
    private javax.swing.JLabel label_contrasena;
    private javax.swing.JLabel label_email;
    private javax.swing.JLabel label_genero;
    private javax.swing.JLabel label_nombre_usuario;
    private javax.swing.JLabel label_nombres;
    private javax.swing.JLabel label_repetir_contrasena;
    private javax.swing.JLabel label_titulo;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel popup_terminos;
    // End of variables declaration//GEN-END:variables
}
