/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package IGU;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Juan Romero
 */
public class Terminos_y_condiciones extends javax.swing.JFrame {
    
    /**
     * Creates new form Terminos_y_condiciones
     */
    public Terminos_y_condiciones() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/favicon/Nuevo_logo_de_Luminous_Horizons.png")).getImage());
        Text_area.setContentType("text/html"); // Establece el JTextPane para interpretar el texto como HTML
        Text_area.setText(
            "<html>" +
            "<center><h1><b>Términos y Condiciones de Luminous Horizons Agencia de Viajes</b></h1></center><br><br>" +

            "<div style='text-align: justify;'>" +
            "1. <b>Aceptación de los Términos y Condiciones</b><br>" +
            "Al utilizar los servicios de Luminous Horizons Agencia de Viajes, usted acepta cumplir y estar sujeto a los siguientes términos y condiciones. Si no está de acuerdo con alguno de estos términos, le solicitamos que no utilice nuestros servicios.<br><br>" +
            "</div>" +

            "<div style='text-align: justify;'>" +
            "2. <b>Reservaciones y Pagos</b><br>" +
            "2.1. Reservaciones: Las reservaciones de viajes se consideran confirmadas una vez que se recibe el pago correspondiente y se emite una confirmación por escrito.<br>" +
            "2.2. Pagos: Los clientes deben realizar los pagos según las políticas de pago establecidas por Luminous Horizons Agencia de Viajes. Los precios y condiciones de pago pueden variar según el tipo de viaje.<br><br>" +
            "</div>" +

            "<div style='text-align: justify;'>" +
            "3. <b>Cancelaciones y Reembolsos</b><br>" +
            "3.1. Cancelaciones: Las políticas de cancelación varían según el tipo de viaje y proveedor de servicios. Los clientes deben estar informados sobre estas políticas antes de confirmar una reserva.<br>" +
            "3.2. Reembolsos: Los reembolsos se procesarán de acuerdo con las políticas de cancelación aplicables. Luminous Horizons Agencia de Viajes se reserva el derecho de retener tarifas de cancelación según lo estipulado en las políticas.<br><br>" +
            "</div>" +

            "<div style='text-align: justify;'>" +
            "4. <b>Responsabilidad y Seguros</b><br>" +
            "4.1. Luminous Horizons Agencia de Viajes no se hace responsable de pérdidas, daños, lesiones o retrasos que puedan ocurrir durante un viaje. Se recomienda encarecidamente a los clientes obtener un seguro de viaje adecuado.<br><br>" +
            "</div>" +

            "<div style='text-align: justify;'>" +
            "5. <b>Cambios en los Itinerarios</b><br>" +
            "5.1. Luminous Horizons Agencia de Viajes se reserva el derecho de realizar cambios en los itinerarios por razones operativas, de seguridad o fuerza mayor. Los clientes serán notificados de tales cambios en la medida de lo posible.<br><br>" +
            "</div>" +

            "<div style='text-align: justify;'>" +
            "6. <b>Privacidad y Protección de Datos</b><br>" +
            "6.1. Luminous Horizons Agencia de Viajes recopila y utiliza información personal de acuerdo con su política de privacidad. Los clientes pueden revisar esta política en el sitio web de la empresa.<br><br>" +
            "</div>" +

            "<div style='text-align: justify;'>" +
            "7. <b>Derechos de Autor</b><br>" +
            "7.1. El contenido, incluidos textos, imágenes y logotipos, en el sitio web de Luminous Horizons Agencia de Viajes está protegido por derechos de autor. No se permite la reproducción o el uso no autorizado de dicho contenido.<br><br>" +
            "</div>" +

            "<div style='text-align: justify;'>" +
            "8. <b>Ley Aplicable y Jurisdicción</b><br>" +
            "8.1. Estos términos y condiciones se rigen por las leyes vigentes en Perú y cualquier disputa se resolverá en los tribunales de dicha jurisdicción.<br>" +
            "</div>" +
            "</html>"
        );
        
        Text_area.setEnabled(false);
        this.setResizable(false);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Text_area = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TERMINOS Y CONDICIONES");

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        Text_area.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(Text_area);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Terminos_y_condiciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Terminos_y_condiciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Terminos_y_condiciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Terminos_y_condiciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Terminos_y_condiciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane Text_area;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
